import type { SceneSeed } from "../types";

/* ------------------------------------------------------------------ *
 * THE SEED CINÉMATHÈQUE
 *
 * ~30 canonical, real, verifiable film scenes — each with exact film,
 * director, year, the specific scene, and a where-to-watch / timecode
 * hint. The daily pick is a deterministic, date-seeded choice from this
 * list (same day → same scene). Opus can also introduce fresh scenes
 * beyond this list via "Demander".
 *
 * These are deliberately famous and checkable. The deconstruction text
 * is NEVER stored here — it is generated by Opus, under the honesty
 * rule, and cached. This file is just the verified pointer.
 * ------------------------------------------------------------------ */

export const SEEDS: SceneSeed[] = [
  {
    id: "goodfellas-copacabana",
    film: "Goodfellas",
    director: "Martin Scorsese",
    year: 1990,
    scene: {
      fr: "Le plan-séquence du Copacabana — Henry fait entrer Karen par les cuisines",
      en: "The Copacabana long take — Henry walks Karen in through the kitchen",
    },
    whereToWatch: {
      fr: "≈ 30 min dans le film ; un seul plan Steadicam d'environ 3 minutes",
      en: "≈ 30 min in ; a single ~3-minute Steadicam shot",
    },
    mediaQuery: "Goodfellas Martin Scorsese 1990",
    craft: "planséquence",
  },
  {
    id: "psycho-shower",
    film: "Psycho",
    director: "Alfred Hitchcock",
    year: 1960,
    scene: {
      fr: "La scène de la douche — l'assassinat de Marion Crane",
      en: "The shower scene — the murder of Marion Crane",
    },
    whereToWatch: {
      fr: "≈ 47 min ; ~45 secondes, ~50 plans, montés par George Tomasini",
      en: "≈ 47 min ; ~45 seconds, ~50 cuts, edited by George Tomasini",
    },
    mediaQuery: "Psycho Alfred Hitchcock 1960",
    craft: "montage",
  },
  {
    id: "2001-bone-cut",
    film: "2001: A Space Odyssey",
    director: "Stanley Kubrick",
    year: 1968,
    scene: {
      fr: "Le raccord os-vaisseau — l'os lancé devient un satellite",
      en: "The bone-to-satellite match cut",
    },
    whereToWatch: {
      fr: "Fin de « The Dawn of Man », ≈ 20 min ; un seul raccord",
      en: "End of “The Dawn of Man”, ≈ 20 min ; a single cut",
    },
    mediaQuery: "2001 A Space Odyssey Stanley Kubrick 1968",
    craft: "montage",
  },
  {
    id: "lawrence-match-cut",
    film: "Lawrence of Arabia",
    director: "David Lean",
    year: 1962,
    scene: {
      fr: "Le raccord de l'allumette au lever de soleil sur le désert",
      en: "The match-to-sunrise cut",
    },
    whereToWatch: {
      fr: "≈ 19 min ; Lawrence souffle l'allumette, coupe sur l'aube du désert",
      en: "≈ 19 min ; Lawrence blows out the match, cut to desert dawn",
    },
    mediaQuery: "Lawrence of Arabia David Lean 1962",
    craft: "montage",
  },
  {
    id: "children-of-men-car",
    film: "Children of Men",
    director: "Alfonso Cuarón",
    year: 2006,
    scene: {
      fr: "L'embuscade dans la voiture — le long plan tournant à l'intérieur",
      en: "The car ambush — the unbroken in-car long take",
    },
    whereToWatch: {
      fr: "≈ 38 min ; plan continu pivotant à 360° dans l'habitacle",
      en: "≈ 38 min ; continuous 360° in-car take",
    },
    mediaQuery: "Children of Men Alfonso Cuarón 2006",
    craft: "planséquence",
  },
  {
    id: "godfather-baptism",
    film: "The Godfather",
    director: "Francis Ford Coppola",
    year: 1972,
    scene: {
      fr: "Le baptême — le montage parallèle baptême / exécutions",
      en: "The baptism — the cross-cut of christening and killings",
    },
    whereToWatch: {
      fr: "Climax, ≈ 2 h 40 ; montage croisé sur l'orgue d'église",
      en: "Climax, ≈ 2h40 ; cross-cut over the church organ",
    },
    mediaQuery: "The Godfather Francis Ford Coppola 1972",
    craft: "montage",
  },
  {
    id: "jaws-dolly-zoom",
    film: "Jaws",
    director: "Steven Spielberg",
    year: 1975,
    scene: {
      fr: "Le travelling compensé sur Brody sur la plage",
      en: "The dolly zoom on Brody at the beach",
    },
    whereToWatch: {
      fr: "≈ 51 min ; l'attaque sur la plage, le visage de Brody",
      en: "≈ 51 min ; the beach attack, on Brody's face",
    },
    mediaQuery: "Jaws Steven Spielberg 1975",
    craft: "lumière",
  },
  {
    id: "there-will-be-blood-milkshake",
    film: "There Will Be Blood",
    director: "Paul Thomas Anderson",
    year: 2007,
    scene: {
      fr: "« I drink your milkshake » — l'affrontement final dans la quille de bowling",
      en: "“I drink your milkshake” — the bowling-alley confrontation",
    },
    whereToWatch: {
      fr: "Finale, ≈ 2 h 30 ; Daniel Plainview et Eli Sunday",
      en: "Finale, ≈ 2h30 ; Daniel Plainview and Eli Sunday",
    },
    mediaQuery: "There Will Be Blood Paul Thomas Anderson 2007",
    craft: "jeu",
  },
  {
    id: "no-country-coin-toss",
    film: "No Country for Old Men",
    director: "Joel and Ethan Coen",
    year: 2007,
    scene: {
      fr: "Le tirage à pile ou face — Chigurh à la station-service",
      en: "The coin toss — Chigurh at the gas station",
    },
    whereToWatch: {
      fr: "≈ 50 min ; « Call it, friendo. »",
      en: "≈ 50 min ; “Call it, friendo.”",
    },
    mediaQuery: "No Country for Old Men Coen brothers 2007",
    craft: "suspense",
  },
  {
    id: "silence-lambs-basement",
    film: "The Silence of the Lambs",
    director: "Jonathan Demme",
    year: 1991,
    scene: {
      fr: "La cave de Buffalo Bill — la vision nocturne et Clarice dans le noir",
      en: "Buffalo Bill's basement — night vision and Clarice in the dark",
    },
    whereToWatch: {
      fr: "Climax, ≈ 1 h 45 ; le POV en vision nocturne",
      en: "Climax, ≈ 1h45 ; the night-vision POV",
    },
    mediaQuery: "The Silence of the Lambs Jonathan Demme 1991",
    craft: "suspense",
  },
  {
    id: "apocalypse-now-opening",
    film: "Apocalypse Now",
    director: "Francis Ford Coppola",
    year: 1979,
    scene: {
      fr: "L'ouverture — la jungle, « The End », et le ventilateur du plafond",
      en: "The opening — the jungle, “The End”, and the ceiling fan",
    },
    whereToWatch: {
      fr: "Générique d'ouverture ; surimpression jungle / chambre d'hôtel",
      en: "Opening title sequence ; jungle dissolves into the hotel room",
    },
    mediaQuery: "Apocalypse Now Francis Ford Coppola 1979",
    craft: "son",
  },
  {
    id: "blade-runner-tears",
    film: "Blade Runner",
    director: "Ridley Scott",
    year: 1982,
    scene: {
      fr: "« Tears in rain » — le monologue final de Roy Batty sur le toit",
      en: "“Tears in rain” — Roy Batty's final monologue on the rooftop",
    },
    whereToWatch: {
      fr: "Climax sur le toit, sous la pluie ; la colombe",
      en: "Rooftop climax, in the rain ; the dove",
    },
    mediaQuery: "Blade Runner Ridley Scott 1982",
    craft: "jeu",
  },
  {
    id: "mad-max-fury-road-storm",
    film: "Mad Max: Fury Road",
    director: "George Miller",
    year: 2015,
    scene: {
      fr: "L'entrée dans la tempête de sable",
      en: "Driving into the sandstorm",
    },
    whereToWatch: {
      fr: "≈ 30 min ; la première grande poursuite vers le mur de poussière",
      en: "≈ 30 min ; the first big chase into the dust wall",
    },
    mediaQuery: "Mad Max Fury Road George Miller 2015",
    craft: "montage",
  },
  {
    id: "raging-bull-fight",
    film: "Raging Bull",
    director: "Martin Scorsese",
    year: 1980,
    scene: {
      fr: "Un combat sur le ring — le ralenti, les flashs, le son subjectif",
      en: "A ring fight — slow motion, flashbulbs, subjective sound",
    },
    whereToWatch: {
      fr: "Les séquences de boxe ; LaMotta vs Robinson",
      en: "The boxing sequences ; LaMotta vs Robinson",
    },
    mediaQuery: "Raging Bull Martin Scorsese 1980",
    craft: "son",
  },
  {
    id: "shining-tricycle",
    film: "The Shining",
    director: "Stanley Kubrick",
    year: 1980,
    scene: {
      fr: "Danny en tricycle — le Steadicam dans les couloirs de l'Overlook",
      en: "Danny on the tricycle — Steadicam through the Overlook halls",
    },
    whereToWatch: {
      fr: "≈ 38 min ; le suivi au ras du sol jusqu'aux jumelles",
      en: "≈ 38 min ; the low tracking shot up to the twins",
    },
    mediaQuery: "The Shining Stanley Kubrick 1980",
    craft: "planséquence",
  },
  {
    id: "in-the-mood-for-love-stairs",
    film: "In the Mood for Love",
    director: "Wong Kar-wai",
    year: 2000,
    scene: {
      fr: "Les croisements dans l'escalier des nouilles — le ralenti sur Yumeji's Theme",
      en: "The noodle-stall stairwell — slow motion to Yumeji's Theme",
    },
    whereToWatch: {
      fr: "Motif répété tôt dans le film ; ralenti, musique de Shigeru Umebayashi",
      en: "Recurring early motif ; slow motion, Shigeru Umebayashi's score",
    },
    mediaQuery: "In the Mood for Love Wong Kar-wai 2000",
    craft: "lumière",
  },
  {
    id: "seven-samurai-rain-battle",
    film: "Seven Samurai",
    director: "Akira Kurosawa",
    year: 1954,
    scene: {
      fr: "La bataille finale sous la pluie",
      en: "The final battle in the rain",
    },
    whereToWatch: {
      fr: "Climax ; multi-caméras, téléobjectifs, boue et pluie",
      en: "Climax ; multi-camera, telephoto lenses, mud and rain",
    },
    mediaQuery: "Seven Samurai Akira Kurosawa 1954",
    craft: "montage",
  },
  {
    id: "all-that-jazz-bye-bye",
    film: "All That Jazz",
    director: "Bob Fosse",
    year: 1979,
    scene: {
      fr: "« On Broadway » — le montage de l'audition au matin",
      en: "“On Broadway” — the morning ritual montage",
    },
    whereToWatch: {
      fr: "Séquence d'ouverture répétée ; « It's showtime, folks »",
      en: "Recurring opening sequence ; “It's showtime, folks”",
    },
    mediaQuery: "All That Jazz Bob Fosse 1979",
    craft: "montage",
  },
  {
    id: "vertigo-tower",
    film: "Vertigo",
    director: "Alfred Hitchcock",
    year: 1958,
    scene: {
      fr: "Le clocher — le premier travelling compensé (contra-zoom) dans l'escalier",
      en: "The bell tower — the original dolly-zoom down the stairwell",
    },
    whereToWatch: {
      fr: "Climax dans la tour de la mission ; le vertige de Scottie",
      en: "Mission-tower climax ; Scottie's vertigo",
    },
    mediaQuery: "Vertigo Alfred Hitchcock 1958",
    craft: "lumière",
  },
  {
    id: "parasite-rain-descent",
    film: "Parasite",
    director: "Bong Joon-ho",
    year: 2019,
    scene: {
      fr: "La descente sous la pluie — du quartier riche au sous-sol inondé",
      en: "The rainy descent — from the rich house down to the flooded semi-basement",
    },
    whereToWatch: {
      fr: "≈ 1 h 30 ; la longue descente d'escaliers et de ruelles",
      en: "≈ 1h30 ; the long downhill run of stairs and alleys",
    },
    mediaQuery: "Parasite Bong Joon-ho 2019",
    craft: "montage",
  },
  {
    id: "the-conversation-park",
    film: "The Conversation",
    director: "Francis Ford Coppola",
    year: 1974,
    scene: {
      fr: "L'enregistrement dans Union Square — la conversation reconstruite",
      en: "The Union Square recording — the reconstructed conversation",
    },
    whereToWatch: {
      fr: "Ouverture ; le zoom lent et le brouillage du son",
      en: "Opening ; the slow zoom and the garbled audio",
    },
    mediaQuery: "The Conversation Francis Ford Coppola 1974",
    craft: "son",
  },
  {
    id: "do-the-right-thing-riot",
    film: "Do the Right Thing",
    director: "Spike Lee",
    year: 1989,
    scene: {
      fr: "La poubelle dans la vitrine — l'émeute devant la pizzeria de Sal",
      en: "The trash can through the window — the riot outside Sal's",
    },
    whereToWatch: {
      fr: "Climax ; Mookie, la chaleur, la bascule",
      en: "Climax ; Mookie, the heat, the turn",
    },
    mediaQuery: "Do the Right Thing Spike Lee 1989",
    craft: "jeu",
  },
  {
    id: "whiplash-finale",
    film: "Whiplash",
    director: "Damien Chazelle",
    year: 2014,
    scene: {
      fr: "Le solo final — « Caravan » et le duel de regards",
      en: "The final solo — “Caravan” and the duel of looks",
    },
    whereToWatch: {
      fr: "Climax ; le montage du solo de batterie de Neiman",
      en: "Climax ; the cut of Neiman's drum solo",
    },
    mediaQuery: "Whiplash Damien Chazelle 2014",
    craft: "montage",
  },
  {
    id: "touch-of-evil-opening",
    film: "Touch of Evil",
    director: "Orson Welles",
    year: 1958,
    scene: {
      fr: "Le plan-séquence d'ouverture — la bombe dans la voiture",
      en: "The opening long take — the bomb in the car",
    },
    whereToWatch: {
      fr: "Générique d'ouverture ; ~3 min en une grue continue",
      en: "Opening titles ; ~3 min in a single crane shot",
    },
    mediaQuery: "Touch of Evil Orson Welles 1958",
    craft: "planséquence",
  },
  {
    id: "the-battle-of-algiers-casbah",
    film: "The Battle of Algiers",
    director: "Gillo Pontecorvo",
    year: 1966,
    scene: {
      fr: "Les trois femmes posent les bombes dans la ville",
      en: "The three women plant the bombs in the city",
    },
    whereToWatch: {
      fr: "≈ 1 h ; montage parallèle, tambour de Morricone",
      en: "≈ 1h ; cross-cut, Morricone's drum",
    },
    mediaQuery: "The Battle of Algiers Gillo Pontecorvo 1966",
    craft: "montage",
  },
  {
    id: "once-upon-a-time-west-opening",
    film: "Once Upon a Time in the West",
    director: "Sergio Leone",
    year: 1968,
    scene: {
      fr: "L'attente à la gare — les trois hommes et la mouche",
      en: "The station wait — three men and the fly",
    },
    whereToWatch: {
      fr: "Générique d'ouverture ; ~10 min presque sans dialogue",
      en: "Opening titles ; ~10 min nearly wordless",
    },
    mediaQuery: "Once Upon a Time in the West Sergio Leone 1968",
    craft: "son",
  },
  {
    id: "the-third-man-ferris-wheel",
    film: "The Third Man",
    director: "Carol Reed",
    year: 1949,
    scene: {
      fr: "La grande roue — le discours du coucou de Harry Lime",
      en: "The Ferris wheel — Harry Lime's cuckoo-clock speech",
    },
    whereToWatch: {
      fr: "≈ 1 h 15 ; Vienne, la cithare d'Anton Karas",
      en: "≈ 1h15 ; Vienna, Anton Karas's zither",
    },
    mediaQuery: "The Third Man Carol Reed 1949",
    craft: "jeu",
  },
  {
    id: "moonlight-ocean",
    film: "Moonlight",
    director: "Barry Jenkins",
    year: 2016,
    scene: {
      fr: "La leçon de natation — Juan tient Chiron dans l'eau",
      en: "The swimming lesson — Juan holds Chiron in the water",
    },
    whereToWatch: {
      fr: "1er chapitre « Little » ; la mer, la lumière, le baptême",
      en: "First chapter “Little” ; the sea, the light, the baptism",
    },
    mediaQuery: "Moonlight Barry Jenkins 2016",
    craft: "lumière",
  },
  {
    id: "the-graduate-ending",
    film: "The Graduate",
    director: "Mike Nichols",
    year: 1967,
    scene: {
      fr: "Le bus, après l'église — les deux visages qui se décomposent",
      en: "The bus, after the church — the two faces falling",
    },
    whereToWatch: {
      fr: "Plan final ; le sourire qui s'éteint sur « The Sound of Silence »",
      en: "Final shot ; the smile fading over “The Sound of Silence”",
    },
    mediaQuery: "The Graduate Mike Nichols 1967",
    craft: "jeu",
  },
  {
    id: "rear-window-watching",
    film: "Rear Window",
    director: "Alfred Hitchcock",
    year: 1954,
    scene: {
      fr: "Jefferies observe — le montage du regard à la cour intérieure",
      en: "Jefferies watches — the editing of looking across the courtyard",
    },
    whereToWatch: {
      fr: "Tout au long ; la grammaire du champ / contrechamp du voyeur",
      en: "Throughout ; the watcher's shot/reaction-shot grammar",
    },
    mediaQuery: "Rear Window Alfred Hitchcock 1954",
    craft: "suspense",
  },
];

/** Deterministic daily index: same calendar day → same scene. */
export function seedForDate(dateStr: string): SceneSeed {
  // Hash the YYYY-MM-DD string into a stable index. A small FNV-1a is
  // plenty here and stays identical across runs/devices.
  let h = 0x811c9dc5;
  for (let i = 0; i < dateStr.length; i++) {
    h ^= dateStr.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  const idx = Math.abs(h) % SEEDS.length;
  return SEEDS[idx];
}

export function seedById(id: string): SceneSeed | undefined {
  return SEEDS.find((s) => s.id === id);
}
